=== obsolete-gjo-se/2009_native_PJ09_XXEO_fincazentrale/relaunch/objects/edomizil/Attributs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Attributs">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Attribut" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Nr">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Attributsnummer</xs:documentation>
									<xs:documentation xml:lang="EN">Number of attribute</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="KategorieNr">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Nummer der Attributkategorie</xs:documentation>
									<xs:documentation xml:lang="EN">Number of attribute category</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="Typ">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Attributstyp</xs:documentation>
									<xs:documentation xml:lang="EN">Type of attribute; Reference to AttributTypes.xml</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="Minimalwert" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Kleinstwert für Attribut, wenn notwendig</xs:documentation>
									<xs:documentation xml:lang="EN">Minimum value for attribute if it is necessary</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="Maximalwert" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Höchstwert für Attribut, wenn notwendig</xs:documentation>
									<xs:documentation xml:lang="EN">Maximum value for attribute if it is necessary</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="AttributDE">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Deutscher Name des Attributs</xs:documentation>
									<xs:documentation xml:lang="EN">German name of attribute</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="AttributEN" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Englischer Name des Attributs</xs:documentation>
									<xs:documentation xml:lang="EN">English name of attribute</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="AttributFR" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Französischer Name des Attributs</xs:documentation>
									<xs:documentation xml:lang="EN">French name of attribute</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="AttributSP" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Spanischer Name des Attributs</xs:documentation>
									<xs:documentation xml:lang="EN">Spanish name of attribute</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="AttributIT" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Italienischer Name des Attributs</xs:documentation>
									<xs:documentation xml:lang="EN">Italian name of attribute</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="EinheitDE" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Deutscher Name der Attributseinheit</xs:documentation>
									<xs:documentation xml:lang="EN">German name of attribute unit</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="EinheitEN" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Englischer Name der Attributseinheit</xs:documentation>
									<xs:documentation xml:lang="EN">English name of attribute unit</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="EinheitFR" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Französischer Name der Attributseinheit</xs:documentation>
									<xs:documentation xml:lang="EN">French name of attribute unit</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="EinheitSP" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Spanischer Name der Attributseinheit</xs:documentation>
									<xs:documentation xml:lang="EN">Spanish name of attribute unit</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="EinheitIT" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Italienischer Name der Attributseinheit</xs:documentation>
									<xs:documentation xml:lang="EN">Italian name of attribute unit</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="Lookup" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">ID der Lookup-Gruppe</xs:documentation>
									<xs:documentation xml:lang="EN">ID of Lookup-group</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== obsolete-gjo-se/2009_native_PJ09_XXEO_fincazentrale/relaunch/objects/edomizil/Attributs.xml
<?xml version="1.0" encoding="UTF-8"?>
<Attributs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.e-domizil.de/Schnittstellen/XML/Attributs.xsd">
  <Attribut>
    <Nr>113</Nr>
    <KategorieNr>1</KategorieNr>
    <Typ>6</Typ>
    <Maximalwert>0</Maximalwert>
    <AttributDE>Art des Objektes</AttributDE>
    <AttributEN>Property type</AttributEN>
    <AttributFR>Type d' objet</AttributFR>
    <AttributSP>Tipo de alojamiento</AttributSP>
    <AttributIT>Tipo di oggetto</AttributIT>
    <Lookup>ObjektArt</Lookup>
  </Attribut>
  <Attribut>
    <Nr>114</Nr>
    <KategorieNr>1</KategorieNr>
    <Typ>5</Typ>
    <Maximalwert>0</Maximalwert>
    <AttributDE>Nutzung</AttributDE>
    <AttributEN>Use</AttributEN>
    <AttributFR>Utilisation</AttributFR>
    <AttributSP>uso</AttributSP>
    <AttributIT>Uso</AttributIT>
    <Lookup>Nutzung</Lookup>
  </Attribut>
  <Attribut>
    <Nr>115</Nr>
    <KategorieNr>1</KategorieNr>
    <Typ>6</Typ>
    <Maximalwert>0</Maximalwert>
    <AttributDE>Ferienobjektkategorie</AttributDE>
    <AttributEN>Holiday category</AttributEN>
    <AttributFR>Catégorie d'objet de vacances</AttributFR>
    <AttributSP>Categoría de alojamiento de vacaciones</AttributSP>
    <AttributIT>Categoria oggetti per ferie</AttributIT>
    <Lookup>Objektkategorie</Lookup>
  </Attribut>
  <Attribut>
    <Nr>116</Nr>
    <KategorieNr>1</KategorieNr>
    <Typ>6</Typ>
    <Maximalwert>0</Maximalwert>
    <AttributDE>Angaben zum Gesamtobjekt</AttributDE>
    <AttributEN>Specifications of the holiday home</AttributEN>
    <AttributFR>Spécifications de la maison</AttributFR>
    <AttributSP>información sobre el conjunto del inmueble</AttributSP>
    <AttributIT>Dati sull'oggetto completo</AttributIT>
    <Lookup>ObjektLage</Lookup>
  </Attribut>
  <Attribut>
    <Nr>117</Nr>
    <KategorieNr>1</KategorieNr>
    <Typ>5</Typ>
    <Maximalwert>0</Maximalwert>
    <AttributDE>Äußerer Gesamteindruck</AttributDE>
    <AttributEN>Exterior overall impression</AttributEN>
    <AttributFR>Impression extérieure générale</AttributFR>
    <AttributSP>Impresión general exterior</AttributSP>
    <AttributIT>Impressione generale degli esterni</AttributIT>
    <Lookup>AussenEindruck</Lookup>
  </Attribut>
  <Attribut>
    <Nr>118</Nr>
    <KategorieNr>1</KategorieNr>
    <Typ>5</Typ>
    <Maximalwert>0</Maximalwert>
    <AttributDE>Gesamteindruck Möblierung und Ausstattung</AttributDE>
    <AttributEN>Overall impression furnishing and features</AttributEN>
    <AttributFR>Impression générale ameublement et équipement</AttributFR>
    <AttributSP>Impresión general mobiliario y equipamiento</AttributSP>
    <AttributIT>Impressione generale di arredamento e dotazioni</AttributIT>
    <Lookup>GesamteindruckMöbel</Lookup>
  </Attribut>
  <Attribut>
    <Nr>119</Nr>
    <KategorieNr>1</KategorieNr>
    <Typ>2</Typ>
    <Maximalwert>2050</Maximalwert>
    <AttributDE>Vermietung seit</AttributDE>
    <AttributEN>Let since</AttributEN>
    <AttributFR>Location depuis</AttributFR>
    <AttributSP>Se alquila desde</AttributSP>
    <AttributIT>Affitto dal</AttributIT>
  </Attribut>
  <Attribut>
    <Nr>120</Nr>
    <KategorieNr>1</KategorieNr>
    <Typ>2</Typ>
    <Maximalwert>2050</Maximalwert>
    <AttributDE>Letzte Renovierung Außenbereich</AttributDE>
    <AttributEN>Last external renovation</AttributEN>
    <AttributFR>Dernière rénovation extérieure</AttributFR>
    <AttributSP>Última reforma exterior</AttributSP>
    <AttributIT>Data ultimo rinnovo zona esterna</AttributIT>
  </Attribut>
  <Attribut>
    <Nr>121</Nr>
    <KategorieNr>1</KategorieNr>
    <Typ>2</Typ>
    <Maximalwert>2050</Maximalwert>
    <AttributDE>Letzte Renovierung Innenbereich</AttributDE>
    <AttributEN>Last internal renovation</AttributEN>
    <AttributFR>Dernière rénovation intérieure</AttributFR>
    <AttributSP>Última reforma interior</AttributSP>
    <AttributIT>Data ultimo rinnovo zona interna</AttributIT>
  </Attribut>
  <Attribut>
    <Nr>122</Nr>
    <KategorieNr>1</KategorieNr>
    <Typ>2</Typ>
    <Maximalwert>2050</Maximalwert>
    <AttributDE>Letzte Renovierung Sanitärbereich</AttributDE>
    <AttributEN>Last sanitary renovation</AttributEN>
    <AttributFR>Dernière rénovation des sanitaires</AttributFR>
    <AttributSP>última reforma sanitarios</AttributSP>
    <AttributIT>Data ultimo rinnovo sanitari</AttributIT>
  </Attribut>
  <Attribut>
    <Nr>124</Nr>
    <KategorieNr>1</KategorieNr>
    <Typ>2</Typ>
    <Maximalwert>10</Maximalwert>
    <AttributDE>Anzahl Wohnzimmer</AttributDE>
    <AttributEN>Number of living rooms</AttributEN>
    <AttributFR>Nombre total de pièces</AttributFR>
    <AttributSP>Nº de salones</AttributSP>
    <AttributIT>Totale soggiorno</AttributIT>
  </Attribut>
  <Attribut>
    <Nr>125</Nr>
    <KategorieNr>1</KategorieNr>
    <Typ>2</Typ>
    <Minimalwert>0</Minimalwert>
    <Maximalwert>1000</Maximalwert>
    <AttributDE>Wohnfläche</AttributDE>
    <AttributEN>Living area</AttributEN>
    <AttributFR>Surface de logement</AttributFR>
    <AttributSP>Superficie útil</AttributSP>
    <AttributIT>Superficie abitabile</AttributIT>
    <EinheitDE>m²</EinheitDE>
    <EinheitEN>m²</EinheitEN>
    <EinheitFR>m²</EinheitFR>
    <EinheitSP>m²</EinheitSP>
    <EinheitIT>m²</EinheitIT>
  </Attribut>
  <Attribut>
    <Nr>126</Nr>
    <KategorieNr>1</KategorieNr>
    <Typ>3</Typ>
    <Maximalwert>0</Maximalwert>
    <AttributDE>Grundstücksfläche</AttributDE>
    <AttributEN>Property area</AttributEN>
    <AttributFR>Surface de terrain</AttributFR>
    <AttributSP>Superficie del terreno</AttributSP>
    <AttributIT>Superficie del terreno</AttributIT>
    <EinheitDE>m²</EinheitDE>
    <EinheitEN>m²</EinheitEN>
    <EinheitFR>m²</EinheitFR>
    <EinheitSP>m²</EinheitSP>
    <EinheitIT>m²</EinheitIT>
  </Attribut>
  <Attribut>
    <Nr>127</Nr>
    <KategorieNr>1</KategorieNr>
    <Typ>2</Typ>
    <Minimalwert>1</Minimalwert>
    <Maximalwert>30</Maximalwert>
    <AttributDE>Normalbelegung</AttributDE>
    <AttributEN>Normal occupancy</AttributEN>
    <AttributFR>Occupation normale</AttributFR>
    <AttributSP>Ocupación normal</AttributSP>
    <AttributIT>Numero standard persone</AttributIT>
    <EinheitDE>Personen</EinheitDE>
    <EinheitEN>Persons</EinheitEN>
    <EinheitFR>Personnes</EinheitFR>
    <EinheitSP>Personas</EinheitSP>
    <EinheitIT>Persone</EinheitIT>
  </Attribut>
  <Attribut>
    <Nr>128</Nr>
    <KategorieNr>1</KategorieNr>
    <Typ>2</Typ>
    <Minimalwert>1</Minimalwert>
    <Maximalwert>30</Maximalwert>
    <AttributDE>Maximalbelegung</AttributDE>
    <AttributEN>Maximum occupancy</AttributEN>
    <AttributFR>Occupation maximale</AttributFR>
    <AttributSP>Ocupación máxima</AttributSP>
    <AttributIT>Numero massimo persone</AttributIT>
    <EinheitDE>Personen</EinheitDE>
    <EinheitEN>Persons</EinheitEN>
    <EinheitFR>Personnes</EinheitFR>
    <EinheitSP>Personas</EinheitSP>
    <EinheitIT>Persone</EinheitIT>
  </Attribut>
  <Attribut>
    <Nr>129</Nr>
    <KategorieNr>13</KategorieNr>
    <Typ>5</Typ>
    <Maximalwert>99</Maximalwert>
    <AttributDE>Heizung</AttributDE>
    <AttributEN>Heating</AttributEN>
    <AttributFR>Chauffage</AttributFR>
    <AttributSP>Calefacción</AttributSP>
    <AttributIT>Riscaldamento</AttributIT>
    <Lookup>Heizung</Lookup>
  </Attribut>
  <Attribut>
    <Nr>130</Nr>
    <KategorieNr>13</KategorieNr>
    <Typ>5</Typ>
    <Maximalwert>0</Maximalwert>
    <AttributDE>Klimatisierung</AttributDE>
    <AttributEN>Air conditioning</AttributEN>
    <AttributFR>Air conditionné</AttributFR>
    <AttributSP>Climatización</AttributSP>
    <AttributIT>Impianto di condizionamento</AttributIT>
    <Lookup>Klimatisierung</Lookup>
  </Attribut>
  <Attribut>
    <Nr>131</Nr>
    <KategorieNr>13</KategorieNr>
    <Typ>6</Typ>
    <Maximalwert>0</Maximalwert>
    <AttributDE>Unterhaltungselektronik</AttributDE>
    <AttributEN>Entertainment electronics</AttributEN>
    <AttributFR>Électronique de divertissement</AttributFR>
    <AttributSP>Equipos de imagen y sonido</AttributSP>
    <AttributIT>Elettronica per il tempo libero</AttributIT>
    <Lookup>Elektronik</Lookup>
  </Attribut>
  <Attribut>
    <Nr>132</Nr>
    <KategorieNr>13</KategorieNr>
    <Typ>1</Typ>
    <Maximalwert>0</Maximalwert>
    <AttributDE>Sonstige Unterhaltungselektronik</AttributDE>
    <AttributEN>Other entertainment electronics</AttributEN>
    <AttributFR>Autre électronique de divertissement</AttributFR>
    <AttributSP>Otros imagen y sonido</AttributSP>
    <AttributIT>Altra elettronica per il tempo libero</AttributIT>
  </Attribut>
  <Attribut>
    <Nr>133</Nr>
    <KategorieNr>13</KategorieNr>
    <Typ>6</Typ>
    <Maximalwert>0</Maximalwert>
    <AttributDE>Telekommunikation</AttributDE>
    <AttributEN>Telecommunications</AttributEN>
    <AttributFR>Télécommunications</AttributFR>
    <AttributSP>Telecomunicaciones</AttributSP>
    <AttributIT>Telecomunicazioni</AttributIT>
    <Lookup>Telekom</Lookup>
  </Attribut>
  <Attribut>
    <Nr>134</Nr>
    <KategorieNr>52</KategorieNr>
    <Typ>6</Typ>
    <Maximalwert>0</Maximalwert>
    <AttributDE>Parkmöglichkeiten</AttributDE>
    <AttributEN>Parking facilities</AttributEN>
    <AttributFR>Possibilités de parking</AttributFR>
    <AttributSP>Posibilidad de aparcamiento</AttributSP>
    <AttributIT>Parcheggi disponibili</AttributIT>
    <Lookup>Parken</Lookup>
  </Attribut>
  <Attribut>
    <Nr>135</Nr>
    <KategorieNr>13</KategorieNr>
    <Typ>6</Typ>
    <Maximalwert>0</Maximalwert>
    <AttributDE>Einrichtungen</AttributDE>
    <AttributEN>Equipment</AttributEN>
    <AttributFR>Autres équipements</AttributFR>
    <AttributSP>Equipamiento</AttributSP>
    <AttributIT>Arredi</AttributIT>
    <Lookup>InfrastrukturSonst</Lookup>
  </Attribut>
  <Attribut>
    <Nr>136</Nr>
    <KategorieNr>4</KategorieNr>
    <Typ>2</Typ>
    <Maximalwert>500</Maximalwert>
    <AttributDE>Größe Wohnzimmer</AttributDE>
