=== obsolete-gjo-se/2009_native_PJ09_XXEO_fincazentrale/relaunch/objects/edomizil/abarbeiten/AttributLookups.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="AttributLookups">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AttributeLookup" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Nr">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Nummer des Lookup-Elements</xs:documentation>
									<xs:documentation xml:lang="EN">Number of the Lookup-element</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="ID">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Eindeutige ID der Lookup-Gruppe; Referenz zur Datei Attributes.xml, Element "Lookup"</xs:documentation>
									<xs:documentation xml:lang="EN">ID of Lookup-group; Reference to Attributes.xml, Element "Lookup"</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="WertDE">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Deutscher Name des Lookup-Elements</xs:documentation>
									<xs:documentation xml:lang="EN">German name of the Lookup-element</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="WertEN" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Englischer Name des Lookup-Elements</xs:documentation>
									<xs:documentation xml:lang="EN">English name of the Lookup-element</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="WertFR" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Französischer Name des Lookup-Elements</xs:documentation>
									<xs:documentation xml:lang="EN">French name of the Lookup-element</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="WertSP" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Spanischer Name des Lookup-Elements</xs:documentation>
									<xs:documentation xml:lang="EN">Spanish name of the Lookup-element</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="WertIT" minOccurs="0">
								<xs:annotation>
									<xs:documentation xml:lang="DE">Italienischer Name des Lookup-Elements</xs:documentation>
									<xs:documentation xml:lang="EN">Italian name of the Lookup-element</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== obsolete-gjo-se/2009_native_PJ09_XXEO_fincazentrale/relaunch/objects/edomizil/abarbeiten/AttributLookups.xml
<?xml version="1.0" encoding="UTF-8"?>
<AttributLookups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.e-domizil.de/Schnittstellen/XML/AttributLookups.xsd">
  <AttributeLookup>
    <Nr>181</Nr>
    <ID>Küche</ID>
    <WertDE>Espressomaschine</WertDE>
    <WertEN>Espresso machine</WertEN>
    <WertFR>Machine à café expresso</WertFR>
    <WertSP>Máquina de café</WertSP>
    <WertIT>Macchina espresso</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>182</Nr>
    <ID>Parken</ID>
    <WertDE>Privatparkplatz auf Grundstück/Hofanlage</WertDE>
    <WertEN>Private parking on site</WertEN>
    <WertFR>Parking privé</WertFR>
    <WertSP>Aparcamiento privado en terreno/patio</WertSP>
    <WertIT>Parcheggio privato sul terreno / nel cortile</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>183</Nr>
    <ID>SonstigeRäume</ID>
    <WertDE>Abschließbarer Abstellraum</WertDE>
    <WertEN>Lockable storage room</WertEN>
    <WertFR>Débarras verrouillable</WertFR>
    <WertSP>Trastero con cerradura</WertSP>
    <WertIT>Ripostiglio con serratura</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>184</Nr>
    <ID>Parken</ID>
    <WertDE>Öffentlicher Parkplatz</WertDE>
    <WertEN>Public parking</WertEN>
    <WertFR>Aire de stationnement publique</WertFR>
    <WertSP>Aparcamiento público</WertSP>
    <WertIT>Parcheggio pubblico</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>185</Nr>
    <ID>Parken</ID>
    <WertDE>Abschließbare Garage</WertDE>
    <WertEN>Lockable garage</WertEN>
    <WertFR>Garage verrouillable</WertFR>
    <WertSP>Garaje con cerradura</WertSP>
    <WertIT>Garage con serratura</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>186</Nr>
    <ID>Parken</ID>
    <WertDE>Carport</WertDE>
    <WertEN>Carport</WertEN>
    <WertFR>Carport</WertFR>
    <WertSP>Plaza de aparcamiento cubierta</WertSP>
    <WertIT>Carport</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>187</Nr>
    <ID>Objektkategorie</ID>
    <WertDE>Aktivurlaub</WertDE>
    <WertEN>Active holiday</WertEN>
    <WertFR>Vacances actives</WertFR>
    <WertSP>Vacaciones activas</WertSP>
    <WertIT>Vacanze attive</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>189</Nr>
    <ID>Nutzung</ID>
    <WertDE>alleinige Nutzung</WertDE>
    <WertEN>Exclusive use</WertEN>
    <WertFR>utilisation individuelle</WertFR>
    <WertSP>uso exclusivo</WertSP>
    <WertIT>Uso esclusivo</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>190</Nr>
    <ID>Sonstiges</ID>
    <WertDE>Allergikergeeignet</WertDE>
    <WertEN>Suitable for allergic persons</WertEN>
    <WertFR>Adapté aux personnes allergiques</WertFR>
    <WertSP>apto para alérgicos</WertSP>
    <WertIT>Adatto per allergici</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>191</Nr>
    <ID>Sport</ID>
    <WertDE>Angeln</WertDE>
    <WertEN>Fishing</WertEN>
    <WertFR>Pêche à la ligne</WertFR>
    <WertSP>Pesca</WertSP>
    <WertIT>Pescare</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>192</Nr>
    <ID>Freizeit</ID>
    <WertDE>Außenswimmingpool</WertDE>
    <WertEN>Outdoor swimming pool</WertEN>
    <WertFR>Piscine extérieure</WertFR>
    <WertSP>Piscina al aire libre</WertSP>
    <WertIT>Piscina esterna</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>194</Nr>
    <ID>Küche</ID>
    <WertDE>Dunstabzugshaube</WertDE>
    <WertEN>Extractor hood</WertEN>
    <WertFR>Hotte d'aération</WertFR>
    <WertSP>Campana extractora</WertSP>
    <WertIT>Cappa aspirafumi</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>195</Nr>
    <ID>Sport</ID>
    <WertDE>Basketball</WertDE>
    <WertEN>Basketball</WertEN>
    <WertFR>Basketball</WertFR>
    <WertSP>Baloncesto</WertSP>
    <WertIT>Pallacanestro</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>196</Nr>
    <ID>Bad</ID>
    <WertDE>Badewanne mit Duschvorrichtung</WertDE>
    <WertEN>Bath tub with shower</WertEN>
    <WertFR>Baignoire avec dispositif de douche</WertFR>
    <WertSP>Bañera con ducha</WertSP>
    <WertIT>Vasca da bagno con doccia</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>197</Nr>
    <ID>Bad</ID>
    <WertDE>Badewanne ohne Duschvorrichtung</WertDE>
    <WertEN>Bath tub without shower</WertEN>
    <WertFR>Baignoire sans dispositif de douche</WertFR>
    <WertSP>Bañera sin ducha</WertSP>
    <WertIT>Vasca da bagno senza doccia</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>198</Nr>
    <ID>Sport</ID>
    <WertDE>Bergsteigen</WertDE>
    <WertEN>Mountain climbing</WertEN>
    <WertFR>Ascension</WertFR>
    <WertSP>Alpinismo</WertSP>
    <WertIT>Scalare</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>199</Nr>
    <ID>ObjektArt</ID>
    <WertDE>Bauernhaus</WertDE>
    <WertEN>Farmhouse</WertEN>
    <WertFR>Ferme</WertFR>
    <WertSP>Casa rural</WertSP>
    <WertIT>Agriturismo</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>200</Nr>
    <ID>Objektkategorie</ID>
    <WertDE>Beauty and Wellness</WertDE>
    <WertEN>Beauty and wellness</WertEN>
    <WertFR>Beauté et bien-être</WertFR>
    <WertSP>Belleza y bienestar</WertSP>
    <WertIT>Beauty and Wellness</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>201</Nr>
    <ID>Aussicht</ID>
    <WertDE>Meer/See</WertDE>
    <WertEN>Sea/lake</WertEN>
    <WertFR>Mer/lac</WertFR>
    <WertSP>Mar/Lago</WertSP>
    <WertIT>Mare / Lago</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>202</Nr>
    <ID>Sport</ID>
    <WertDE>Bolzplatz</WertDE>
    <WertEN>Football area</WertEN>
    <WertFR>Terrain de jeu</WertFR>
    <WertSP>Cancha de fútbol</WertSP>
    <WertIT>Campetto da calcio</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>204</Nr>
    <ID>Bad</ID>
    <WertDE>Separate Dusche</WertDE>
    <WertEN>Separate shower</WertEN>
    <WertFR>Cabine de douche séparée</WertFR>
    <WertSP>Ducha separada</WertSP>
    <WertIT>Doccia separata</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>206</Nr>
    <ID>AnbindungSommer</ID>
    <WertDE>Bis 100-500m Nähe zum Objekt</WertDE>
    <WertEN>Within a 100-500m proximity of the holiday home</WertEN>
    <WertFR>A 100-500m de proximité de la maison</WertFR>
    <WertSP>hasta 100-500 ms del alojamiento</WertSP>
    <WertIT>Fino a 100-500m dall'oggetto</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>207</Nr>
    <ID>AnbindungWinter</ID>
    <WertDE>Bis 100-500m Nähe zum Objekt</WertDE>
    <WertEN>Within a 100-500m proximity of  the holiday home</WertEN>
    <WertFR>A 100-500m de proximité de la maison</WertFR>
    <WertSP>hasta 100-500 ms del alojamiento</WertSP>
    <WertIT>Fino a 100-500m dall'oggetto</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>208</Nr>
    <ID>AnbindungSommer</ID>
    <WertDE>Bis 50-100m Nähe zum Objekt</WertDE>
    <WertEN>Within a  50-100m proximity of  the holiday home</WertEN>
    <WertFR>A 50-100m de proximité de la maison</WertFR>
    <WertSP>hasta 50-100 ms del alojamiento</WertSP>
    <WertIT>Fino a 50-100m dall'oggetto</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>209</Nr>
    <ID>AnbindungWinter</ID>
    <WertDE>Bis 50-100m Nähe zum Objekt</WertDE>
    <WertEN>Within a  50-100m proximity of  the holiday home</WertEN>
    <WertFR>A 50-100m de proximité de la maison</WertFR>
    <WertSP>hasta 50-100 ms del alojamiento</WertSP>
    <WertIT>Fino a 50-100m dall'oggetto</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>210</Nr>
    <ID>AnbindungWinter</ID>
    <WertDE>Bis in 50m Nähe zum Objekt</WertDE>
    <WertEN>Within 50m of the holiday home</WertEN>
    <WertFR>A  moins de 50m de proximité de la maison</WertFR>
    <WertSP>hasta 50 ms del alojamiento</WertSP>
    <WertIT>Fino a 50m dall'oggetto</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>211</Nr>
    <ID>AnbindungSommer</ID>
    <WertDE>Bis in 50m Nähe zum Objekt</WertDE>
    <WertEN>Within 50m of the holiday home</WertEN>
    <WertFR>A  moins de 50m de proximité de la maison</WertFR>
    <WertSP>hasta 50 ms del alojamiento</WertSP>
    <WertIT>Fino a 50m dall'oggetto</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>212</Nr>
    <ID>Sport</ID>
    <WertDE>Eislaufen</WertDE>
    <WertEN>Ice skating</WertEN>
    <WertFR>Patin à glace</WertFR>
    <WertSP>Patinaje sobre hielo</WertSP>
    <WertIT>Pattinare</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>214</Nr>
    <ID>Verleih</ID>
    <WertDE>Bootsverleih</WertDE>
    <WertEN>Boat rental service</WertEN>
    <WertFR>Location de bateau</WertFR>
    <WertSP>Alquiler de barcas</WertSP>
    <WertIT>Noleggio barche</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>215</Nr>
    <ID>Service</ID>
    <WertDE>Brötchenservice</WertDE>
    <WertEN>Bakery service</WertEN>
    <WertFR>Service petit-pains</WertFR>
    <WertSP>Servicio de panadería</WertSP>
    <WertIT>Pane a domicilio</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>216</Nr>
    <ID>Parken</ID>
    <WertDE>Abstellplatz in abschließbarer Parkgarage</WertDE>
    <WertEN>Parking space in a lockable garage</WertEN>
    <WertFR>Stationnement dans un garage verrouillable</WertFR>
    <WertSP>Plaza en garaje subterránea con cerradura</WertSP>
    <WertIT>Posto macchina in garage con serratura</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>217</Nr>
    <ID>Elektronik</ID>
    <WertDE>Radio/Radiowecker</WertDE>
    <WertEN>Radio/radio alarm clock</WertEN>
    <WertFR>Radio/radio-réveil</WertFR>
    <WertSP>Radio/radio-despertador</WertSP>
    <WertIT>Radio / Radiosveglia</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>218</Nr>
    <ID>Wohnzimmer</ID>
    <WertDE>Couchecke</WertDE>
    <WertEN>Sofa</WertEN>
    <WertFR>Table basse</WertFR>
    <WertSP>Rincón-salón</WertSP>
    <WertIT>Angolo salotto</WertIT>
  </AttributeLookup>
  <AttributeLookup>
    <Nr>219</Nr>
    <ID>Freizeit</ID>
    <WertDE>Dampfbad</WertDE>
    <WertEN>Steam bath</WertEN>
