=== obsolete-gjo-se/2009_native_PJ09_XXEO_fincazentrale/relaunch/objects/edomizil/abarbeiten/regions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ROOT">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Land" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="SubRegion1" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="SubRegion2" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="SubRegion3" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="Number" type="xs:normalizedString" use="optional">
																<xs:annotation>
																	<xs:documentation xml:lang="DE">Regionsnumber  </xs:documentation>
																	<xs:documentation xml:lang="EN">region code</xs:documentation>
																</xs:annotation>
															</xs:attribute>
															<xs:attribute name="Name_DE" type="xs:normalizedString" use="optional">
																<xs:annotation>
																	<xs:documentation xml:lang="DE">Deutsche Regionsname</xs:documentation>
																	<xs:documentation xml:lang="EN">German region name</xs:documentation>
																</xs:annotation>
															</xs:attribute>
															<xs:attribute name="Name_EN" type="xs:normalizedString" use="optional">
																<xs:annotation>
																	<xs:documentation xml:lang="DE">Englische Regionsname</xs:documentation>
																	<xs:documentation xml:lang="EN">English region name</xs:documentation>
																</xs:annotation>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="Number" type="xs:normalizedString" use="optional">
													<xs:annotation>
														<xs:documentation xml:lang="DE">Regionsnumber  </xs:documentation>
														<xs:documentation xml:lang="EN">region code</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute name="Name_DE" type="xs:normalizedString" use="optional">
													<xs:annotation>
														<xs:documentation xml:lang="DE">Deutsche Regionsname</xs:documentation>
														<xs:documentation xml:lang="EN">German region name</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute name="Name_EN" type="xs:normalizedString" use="optional">
													<xs:annotation>
														<xs:documentation xml:lang="DE">Englische Regionsname</xs:documentation>
														<xs:documentation xml:lang="EN">English region name</xs:documentation>
													</xs:annotation>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="Number" type="xs:normalizedString" use="optional">
										<xs:annotation>
											<xs:documentation xml:lang="DE">Regionsnumber  </xs:documentation>
											<xs:documentation xml:lang="EN">region code</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="Name_DE" type="xs:normalizedString" use="optional">
										<xs:annotation>
											<xs:documentation xml:lang="DE">Deutsche Regionsname</xs:documentation>
											<xs:documentation xml:lang="EN">German region name</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="Name_EN" type="xs:normalizedString" use="optional">
										<xs:annotation>
											<xs:documentation xml:lang="DE">Englische Regionsname</xs:documentation>
											<xs:documentation xml:lang="EN">English region name</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Nr" type="xs:integer" use="required">
							<xs:annotation>
								<xs:documentation xml:lang="DE">Interne Landsnumber  </xs:documentation>
								<xs:documentation xml:lang="EN">Internal land number</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="ISO" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:normalizedString">
									<xs:minLength value="2"/>
									<xs:maxLength value="2"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="Name_DE" type="xs:normalizedString" use="required">
							<xs:annotation>
								<xs:documentation xml:lang="DE">Deutsche Landname</xs:documentation>
								<xs:documentation xml:lang="EN">German land name</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="Name_EN" type="xs:normalizedString" use="required">
							<xs:annotation>
								<xs:documentation xml:lang="DE">Englische Landname</xs:documentation>
								<xs:documentation xml:lang="EN">English land name</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== obsolete-gjo-se/2009_native_PJ09_XXEO_fincazentrale/relaunch/objects/edomizil/Regions.xml
<?xml version="1.0" encoding="UTF-8"?>
<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.e-domizil.de/Schnittstellen/XML/Regions.xsd">
  <Land Nr="123" ISO="EG" Name_DE="Ägypten" Name_EN="Egypt">
    <SubRegion1 Number="1-506" Name_DE="Hurghada" Name_EN="Hurghada">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-402" Name_DE="Sharm El Sheikh" Name_EN="Sharm El Sheikh">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
  </Land>
  <Land Nr="82" ISO="AD" Name_DE="Andorra" Name_EN="Andorra">
    <SubRegion1 Number="1-310" Name_DE="Encamp" Name_EN="Encamp">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
  </Land>
  <Land Nr="137" ISO="AR" Name_DE="Argentinien" Name_EN="Argentina">
    <SubRegion1 Number="1-440" Name_DE="Buenos Aires und Umgebung" Name_EN="Buenos Aires and surroundings">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
  </Land>
  <Land Nr="109" ISO="AU" Name_DE="Australien" Name_EN="Australia">
    <SubRegion1 Number="1-394" Name_DE="Queensland" Name_EN="Queensland">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
  </Land>
  <Land Nr="106" ISO="BB" Name_DE="Barbados" Name_EN="Barbados">
    <SubRegion1 Number="1-371" Name_DE="Insel" Name_EN="Island">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
  </Land>
  <Land Nr="76" ISO="BE" Name_DE="Belgien" Name_EN="Belgium">
    <SubRegion1 Number="1-229" Name_DE="Antwerpen" Name_EN="Antwerp">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-231" Name_DE="Brabant (Flämisch)" Name_EN="Brabant (flemish)">
      <SubRegion2 Number="2-220" Name_DE="Brüssel" Name_EN="Brussels">
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-233" Name_DE="Hennegau (Hainaut)" Name_EN="Hainaut">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-230" Name_DE="Limburg" Name_EN="Limburg">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-235" Name_DE="Lüttich (Liège)" Name_EN="Liège">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-236" Name_DE="Luxemburg" Name_EN="Luxemburg">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-234" Name_DE="Namur (Namen)" Name_EN="Namur">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-227" Name_DE="Ost-Flandern" Name_EN="East-Flanders">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-228" Name_DE="West-Flandern" Name_EN="West-Flanders">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
  </Land>
  <Land Nr="75" ISO="BR" Name_DE="Brasilien" Name_EN="Brasil">
    <SubRegion1 Number="1-405" Name_DE="Der Nordosten" Name_EN="The North-East">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-425" Name_DE="Süden" Name_EN="South">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
  </Land>
  <Land Nr="83" ISO="BG" Name_DE="Bulgarien" Name_EN="Bulgaria">
    <SubRegion1 Number="1-385" Name_DE="Burgas" Name_EN="Burgas">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-392" Name_DE="Varna" Name_EN="Varna">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
  </Land>
  <Land Nr="151" ISO="CN" Name_DE="China" Name_EN="China">
    <SubRegion1 Number="1-495" Name_DE="Peking und Umgebung" Name_EN="Beijing and surrounding">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
  </Land>
  <Land Nr="148" ISO="CR" Name_DE="Costa Rica" Name_EN="Costa Rica">
    <SubRegion1 Number="1-468" Name_DE="Landesinnere" Name_EN="Countryside">
      <SubRegion2>
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
  </Land>
  <Land Nr="36" ISO="DK" Name_DE="Dänemark" Name_EN="Denmark">
    <SubRegion1 Number="1-41" Name_DE="Bornholm" Name_EN="Bornholm">
      <SubRegion2 Number="2-29" Name_DE="Nordbornholm" Name_EN="North Bornholm">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-31" Name_DE="Ostbornholm" Name_EN="East Bornholm">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-30" Name_DE="Südbornholm" Name_EN="South Bornholm">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-32" Name_DE="Westbornholm" Name_EN="West Bornholm">
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-334" Name_DE="Friesische Inseln" Name_EN="Frisian Islands">
      <SubRegion2 Number="2-342" Name_DE="Fanø" Name_EN="Fanø">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-343" Name_DE="Rømø" Name_EN="Rømø">
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-319" Name_DE="Fünen/Langeland/Tasinge" Name_EN="Funen/Langeland/Tasinge">
      <SubRegion2 Number="2-357" Name_DE="Fünen" Name_EN="Funen">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-358" Name_DE="Langeland" Name_EN="Langeland">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-359" Name_DE="Tasinge" Name_EN="Tasinge">
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-90" Name_DE="Jütland" Name_EN="Jutland">
      <SubRegion2 Number="2-340" Name_DE="Djursland/Mols" Name_EN="Djursland/Mols">
        <SubRegion3 Number="3-120" Name_DE="Djursland" Name_EN="Djursland"/>
        <SubRegion3 Number="3-121" Name_DE="Mols" Name_EN="Mols"/>
      </SubRegion2>
      <SubRegion2 Number="2-339" Name_DE="Limfjord" Name_EN="Limfjord">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-316" Name_DE="Nordjütland" Name_EN="North Jutland">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-338" Name_DE="Nordostjütland" Name_EN="Northeast Jutland">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-315" Name_DE="Nordwestjütland" Name_EN="Northwest Jutland">
        <SubRegion3 Number="3-116" Name_DE="Viborg und Umgebung" Name_EN="Viborg and surroundings"/>
        <SubRegion3 Number="3-117" Name_DE="Westliche Gebiete" Name_EN="Western parts"/>
      </SubRegion2>
      <SubRegion2 Number="2-317" Name_DE="Ostjütland" Name_EN="East Jutland">
        <SubRegion3 Number="3-127" Name_DE="Arhus und Umgebung" Name_EN="Arhus and its surroundings"/>
        <SubRegion3 Number="3-128" Name_DE="Vejle und Umgebung" Name_EN="Vejle and its surroundings"/>
      </SubRegion2>
      <SubRegion2 Number="2-318" Name_DE="Südostjütland" Name_EN="Southeast Jutland">
        <SubRegion3 Number="3-125" Name_DE="Sønderjütland" Name_EN="Sønderjutland"/>
      </SubRegion2>
      <SubRegion2 Number="2-341" Name_DE="Westküste" Name_EN="The westcoast">
        <SubRegion3 Number="3-133" Name_DE="Blavand und Umgebung" Name_EN="Blavand and its surroundings"/>
        <SubRegion3 Number="3-123" Name_DE="Ribe und Umgebung" Name_EN="Ribe and its surroundings"/>
        <SubRegion3 Number="3-122" Name_DE="Ringkobing und Umgebung" Name_EN="Ringkobing and its surroundings"/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-44" Name_DE="Seeland" Name_EN="Zealand">
      <SubRegion2 Number="2-360" Name_DE="Nordseeland" Name_EN="North Zealand">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-363" Name_DE="Nordwestseeland" Name_EN="Northwest Zealand">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-361" Name_DE="Südseeland" Name_EN="South Zealand">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-362" Name_DE="Westseeland" Name_EN="West Zealand">
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-320" Name_DE="Südsee-Inseln" Name_EN="Islands of the south seas">
      <SubRegion2 Number="2-355" Name_DE="Falster" Name_EN="Falster">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-354" Name_DE="Lolland" Name_EN="Lolland">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-356" Name_DE="Møn" Name_EN="Møn">
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
  </Land>
  <Land Nr="1" ISO="DE" Name_DE="Deutschland" Name_EN="Germany">
    <SubRegion1 Number="1-29" Name_DE="Baden-Württemberg" Name_EN="Baden-Württemberg">
      <SubRegion2 Number="2-285" Name_DE="Bodensee" Name_EN="Lake Constance">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-424" Name_DE="Rhein-Neckar" Name_EN="Rhein-Neckar">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-298" Name_DE="Schwäbische Alb" Name_EN="Swabian Alb">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-26" Name_DE="Schwarzwald" Name_EN="Black Forest">
        <SubRegion3/>
      </SubRegion2>
    </SubRegion1>
    <SubRegion1 Number="1-30" Name_DE="Bayern" Name_EN="Bavaria">
      <SubRegion2 Number="2-27" Name_DE="Allgäu" Name_EN="Allgaeu">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-28" Name_DE="Berchtesgadener Land" Name_EN="Berchtesgadener Land">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-432" Name_DE="Chiemgau" Name_EN="Chiemgau">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-299" Name_DE="Fichtelgebirge" Name_EN="Fichtelgebirge">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-415" Name_DE="Franken" Name_EN="Franconia">
        <SubRegion3/>
      </SubRegion2>
      <SubRegion2 Number="2-431" Name_DE="Mittelfranken" Name_EN="Middle Franconia">
